name: Deploy Lambda Function
description: 'Deploy Lambda Function'
inputs:
  function_dir:
    description: 'The directory of the function to deploy'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
          node-version: 14.x
          cache: 'npm'
      - name: Install Serverless
        run: |
          make install-serverless
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Deploy Lambda Function
        run: |
          make deploy-function FUNCTION_DIR="{{ inputs.function_dir}}"