name: Code Quality
description: 'Run code quality checks'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '*requirements.txt'
    - name: Upgrade pip
      run: pip install --upgrade pip
      shell: bash
    - name: Install wheel
      run: pip install wheel
      shell: bash
    - name: Install Requirements
      run: pip install -r requirements.txt
      shell: bash
    - name: Install Dev-Test Requirements
      run: pip install -r dev_requirements.txt
      shell: bash
    - name: Local Install
      run: make local-install
      shell: bash
    - name: Run format
      run: make check-format
      shell: bash
    - name: Run lint
      run: make lint
      shell: bash
    - name: Run security
      run: make security-baseline
      shell: bash
    - name: Run static analysis
      run: make complexity-baseline
      shell: bash
