name: Build NodeJS
on:
  workflow_call:
      cache-dependency-path:
        description: Where is your file package.json
        type: string
        default: 'package-lock.json'
      node-js-version:
        description: Your nodejs version
        type: string
        default: '14.X'
jobs:
 build-nodejs:
   runs-on: ubuntu-latest
 steps:
   - name: Use Node.js LTS
     uses: actions/setup-node@v3
     with:
       cache: npm
       cache-dependency-path: '{{ inputs.cache-dependency-path }}'
       node-version: '{{ inputs.node-js-version }}'
   - name: Install dependencies
     run: npm ci
   - name: Build
     run: npm run build